# Generated by Django 5.1.3 on 2024-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed',
        ),
        migrations.AddField(
            model_name='user',
            name='can_receive_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Nombre predeterminado', max_length=255),
            preserve_default=False,
        ),
    ]
