# Generated by Django 3.1.12 on 2025-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
