# Generated by Django 3.1.12 on 2025-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250427_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto de perfil'),
        ),
    ]
