# Generated by Django 3.1.12 on 2025-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250427_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_receive_emails',
            field=models.BooleanField(default=True),
        ),
    ]
