# Generated by Django 3.1.12 on 2025-05-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250506_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.CharField(choices=[('1', '09:00-11:00'), ('2', '11:00-13:00'), ('3', '15:00-17:00'), ('4', '17:00-19:00')], max_length=1),
        ),
    ]
