# Generated by Django 3.1.12 on 2025-05-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250506_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to='diseños/'),
        ),
    ]
