# Generated by Django 3.1.12 on 2025-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_can_receive_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_receive_emails',
            field=models.BooleanField(default=False),
        ),
    ]
