# Generated by Django 3.1.12 on 2025-05-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250502_1347'),
        ('api', '0005_auto_20250502_1204'),
    ]

    operations = [
    ]
