# Generated by Django 3.1.12 on 2025-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250502_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
